name: Feature Request
description: Suggest us to add new feature
labels: ['feature']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form!
        感谢你抽时间提出优化建议，请填写下方的表单完成本次问题的反馈
  - type: input
    id: js-screen-shot-version
    attributes:
      label: Version of js-screen-shot
      description: |
        The exact version of js-screen-shot you are using.
        你所使用的 js-screen-shot 的准确版本。
      placeholder: eg. 1.0.0
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: 你的想法是什么?
      placeholder: 请尽可能详细地告诉我你期望实现一个什么样的功能或者哪里需要进行优化
    validations:
      required: false

